FROM nginx:alpine

COPY ./nginx/app.conf /etc/nginx/conf.d/app.conf
COPY ./html /var/www/html

#RUN chmod 777 /var/www/*
#RUN chmod 777 /var/www/app/*
#RUN chmod 777 /var/www/config/*
#RUN chmod 777 /var/www/css/*
